### ISSUE TITLE
Taiji for Windows

### ISSUE THREAD

**Issue by claraina** [Taiji-pipeline/Taiji#7]
Hello, I am wondering if Taiji is compatible with Windows? I am aware there are pre-built binaries for Mac and Linux, so I have tried to build the program using the instructions for the command line interface. However, when I try to run 'stack install' I get an error, which I have posted [here](https://stackoverflow.com/questions/63145347/stack-install-error-recommended-extra-dep). However, apparently the package I require is not available on Windows so I am very confused. Is someone able to help me? Thank you very much.

**Comment by kaizhang** [comment]
I have not tried Taiji on Windows. Even if it works on Windows, most likely other packages it depends on will not work. I would suggest you try the virtual machine if you are using Windows.

**Comment by treeowl** [comment]
@kaizhang, since Taiji does not (yet?) support Windows, I suggest you make this clear on the installation page so future Windows users won't waste time trying to build it there. Of course, it would also be helpful to consider what might be needed to support Windows! I don't use that platform myself, or know much about it, so I can't help, but there are plenty of others who could.
